version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile.backend
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - agrivision-network

  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - agrivision-network

  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - agrivision-network

networks:
  agrivision-network:

volumes:
  mongo-data:
